services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pvg-frontend:v1.0.0-281226
    container_name: pvg-frontend-prod
    restart: always
    ports:
      - "8081:80"
    networks:
      - pvg_prod_net

networks:
  pvg_prod_net:
    external: true
