services:
  frontend:
    build:
      context: ../frontend/PVG-Solution-FE
      dockerfile: Dockerfile
    image: pvg-frontend:v1.0.0-281226
    container_name: pvg-frontend-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pvg_prod_net
