export const RequestCustomerLabels: Record<string, string> = {
  IsSentEmail: "Đã gửi email",
  phone: "Số điện thoại",
  address: "Địa chỉ",
  redbookaddress: "Địa chỉ sổ đỏ",
  fullname: "Họ và tên",
  EmailTitle: "Tiêu đề email",
  image1: "Hình ảnh 1",
  image2: "Hình ảnh 2",
  image3: "Hình ảnh 3",
  image4: "Hình ảnh 4",
  image5: "Hình ảnh 5",
  companyname: "Tên công ty",
  collateral: "Tài sản đảm bảo",
  dateofissue: "Ngày cấp CCCD",
  age: "Tuổi",
  loanproducttype: "Loại Sản Phẩm Vay",
  jobtitle: "Vị trí việc làm",
  department: "Phòng ban",
  salaryincome: "Thu nhập từ lương",
  monthincome: "Thu nhập hàng tháng",
  nationality: "Quốc tịch",
  gender: "Giới tính",
  placeofissue: "Nơi cấp CCCD",
  otherinfo: "Thông tin khác",
  cmnd: "Chứng minh nhân dân",
  otherincome: "Thu nhập khác",
  matialstatus: "Tình trạng hôn nhân",
  loanamountequested: "Số tiền muốn vay",
  email: "Địa chỉ Email",
  companyphone: "Số điện thoại công ty",
  birthday: "Ngày sinh",
  loanpurpose: "Mục đích vay",
  outstandingloansatotherbanks: "Dư Nợ Tại Các Ngân Hàng Khác",
  cccd: "Căn cước công dân"
};